# Generated by Django 4.1 on 2023-04-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="test",
            field=models.CharField(default=2, max_length=1),
            preserve_default=False,
        ),
    ]
