# Generated by Django 4.1 on 2023-04-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_books_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="test",
            field=models.CharField(default="l", max_length=1),
        ),
    ]
