# Generated by Django 4.1 on 2023-05-07 16:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ToDo",
            new_name="Test",
        ),
    ]
