# Generated by Django 4.1 on 2023-05-07 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0003_nurse"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
