# Generated by Django 4.1 on 2023-05-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0004_delete_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToDo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
            ],
        ),
    ]
