# Generated by Django 4.1 on 2023-05-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0005_todo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="title",
        ),
        migrations.AddField(
            model_name="todo",
            name="todo_title",
            field=models.CharField(default="title", max_length=300),
        ),
    ]
