# Generated by Django 4.1 on 2023-05-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0006_remove_todo_title_todo_todo_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="todo",
            name="todo_content",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="todo",
            name="todo_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="todo",
            name="todo_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="todo",
            name="todo_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="todo",
            name="todo_username",
            field=models.CharField(default="", max_length=100),
        ),
    ]
