# Generated by Django 4.1 on 2023-05-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0007_todo_count_todo_todo_content_todo_todo_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="todo_content",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="todo",
            name="todo_title",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="todo",
            name="todo_username",
            field=models.CharField(max_length=100),
        ),
    ]
